name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password'
        required: true
        default: ''
        type: string
env:
  PASSWORD: "123456"

jobs:

  build:

    runs-on: ubuntu-latest
    if: ${{ inputs.password == env.PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo "Hello"
